//go:build e2e
// +build e2e

package orm1_test

import (
	"context"
	"testing"

	"github.com/hanpama/orm1"
)

func TestBatchSimple(t *testing.T) {
	for _, drv := range []struct {
		name   string
		driver orm1.Driver
	}{
		{"sqlite", sqliteDriver},
		{"postgres", postgresDriver},
	} {
		t.Run(drv.name, func(t *testing.T) {
			ctx := context.Background()

			// Create session factory and register entity
			registry := orm1.NewRegistry()
			registry.Register(&SimpleAuto{}, orm1.WithTable("simple_auto"))
			factory := orm1.NewSessionFactory(registry, drv.driver)

			session := factory.CreateSession()

			// BATCH INSERT - Create multiple entities
			entities := []*SimpleAuto{
				{
					Name:     "test1",
					Nullable: strPtr("nullable1"),
				},
				{
					Name:     "test2",
					Nullable: strPtr("nullable2"),
				},
				{
					Name:     "test3",
					Nullable: strPtr("nullable3"),
				},
			}

			err := session.BatchSave(ctx, entities[0], entities[1], entities[2])
			if err != nil {
				t.Fatalf("BATCH INSERT: BatchSave failed: %v", err)
			}

			// Verify all IDs are set and auto-generated fields populated
			if entities[0].ID == 0 || entities[1].ID == 0 || entities[2].ID == 0 {
				t.Error("BATCH INSERT: expected all IDs to be set")
			}
			if entities[0].AutoGenerated != 42 || entities[1].AutoGenerated != 42 || entities[2].AutoGenerated != 42 {
				t.Error("BATCH INSERT: expected all AutoGenerated to be 42")
			}

			entityIDs := []orm1.Key{
				orm1.NewKey(entities[0].ID),
				orm1.NewKey(entities[1].ID),
				orm1.NewKey(entities[2].ID),
			}

			// BATCH GET - Verify order preservation
			var results []*SimpleAuto
			err = session.BatchGet(ctx, &results, entityIDs)
			if err != nil {
				t.Fatalf("BATCH GET: BatchGet failed: %v", err)
			}

			if len(results) != 3 {
				t.Fatalf("BATCH GET: expected 3 results, got %d", len(results))
			}

			// Verify order: results should match the order of requested keys
			if results[0].ID != entities[0].ID {
				t.Errorf("BATCH GET: expected results[0].ID %d, got %d", entities[0].ID, results[0].ID)
			}
			if results[1].ID != entities[1].ID {
				t.Errorf("BATCH GET: expected results[1].ID %d, got %d", entities[1].ID, results[1].ID)
			}
			if results[2].ID != entities[2].ID {
				t.Errorf("BATCH GET: expected results[2].ID %d, got %d", entities[2].ID, results[2].ID)
			}

			// Verify data integrity
			if results[0].Name != "test1" || results[1].Name != "test2" || results[2].Name != "test3" {
				t.Error("BATCH GET: data mismatch")
			}

			// BATCH GET with non-existent key - Verify nil in results
			nonExistentID := int64(999999)
			mixedIDs := []orm1.Key{
				orm1.NewKey(entities[0].ID),
				orm1.NewKey(nonExistentID), // Non-existent
				orm1.NewKey(entities[2].ID),
			}

			var mixedResults []*SimpleAuto
			err = session.BatchGet(ctx, &mixedResults, mixedIDs)
			if err != nil {
				t.Fatalf("BATCH GET (mixed): BatchGet failed: %v", err)
			}

			if len(mixedResults) != 3 {
				t.Fatalf("BATCH GET (mixed): expected 3 results, got %d", len(mixedResults))
			}

			// Verify order with nil for non-existent key
			if mixedResults[0] == nil || mixedResults[0].ID != entities[0].ID {
				t.Error("BATCH GET (mixed): expected results[0] to be entities[0]")
			}
			if mixedResults[1] != nil {
				t.Error("BATCH GET (mixed): expected results[1] to be nil for non-existent key")
			}
			if mixedResults[2] == nil || mixedResults[2].ID != entities[2].ID {
				t.Error("BATCH GET (mixed): expected results[2] to be entities[2]")
			}

			// BATCH UPDATE - Mix of updates
			results[0].Name = "updated1"
			results[1].Name = "updated2"
			results[2].Name = "updated3"
			results[0].Nullable = strPtr("updated_nullable1")

			err = session.BatchSave(ctx, results[0], results[1], results[2])
			if err != nil {
				t.Fatalf("BATCH UPDATE: BatchSave failed: %v", err)
			}

			// BATCH GET (after update) - Verify updates
			var updatedResults []*SimpleAuto
			err = session.BatchGet(ctx, &updatedResults, entityIDs)
			if err != nil {
				t.Fatalf("BATCH GET (after update): BatchGet failed: %v", err)
			}

			if updatedResults[0].Name != "updated1" || updatedResults[1].Name != "updated2" || updatedResults[2].Name != "updated3" {
				t.Error("BATCH GET (after update): updates not reflected")
			}
			if updatedResults[0].Nullable == nil || *updatedResults[0].Nullable != "updated_nullable1" {
				t.Error("BATCH GET (after update): nullable update not reflected")
			}

			// BATCH SAVE - Mixed INSERT and UPDATE
			newEntity := &SimpleAuto{
				Name:     "test4",
				Nullable: strPtr("nullable4"),
			}

			err = session.BatchSave(ctx, updatedResults[0], newEntity, updatedResults[1])
			if err != nil {
				t.Fatalf("BATCH SAVE (mixed): BatchSave failed: %v", err)
			}

			if newEntity.ID == 0 {
				t.Error("BATCH SAVE (mixed): expected new entity ID to be set")
			}

			// BATCH DELETE
			err = session.BatchDelete(ctx, updatedResults[0], updatedResults[1], updatedResults[2], newEntity)
			if err != nil {
				t.Fatalf("BATCH DELETE: BatchDelete failed: %v", err)
			}

			// BATCH GET (after delete) - Verify all deleted
			var deletedResults []*SimpleAuto
			allIDs := append(entityIDs, orm1.NewKey(newEntity.ID))
			err = session.BatchGet(ctx, &deletedResults, allIDs)
			if err != nil {
				t.Fatalf("BATCH GET (after delete): BatchGet failed: %v", err)
			}

			// All should be nil
			for i, result := range deletedResults {
				if result != nil {
					t.Errorf("BATCH GET (after delete): expected results[%d] to be nil", i)
				}
			}

			// BATCH GET with empty keys
			var emptyResults []*SimpleAuto
			err = session.BatchGet(ctx, &emptyResults, []orm1.Key{})
			if err != nil {
				t.Fatalf("BATCH GET (empty): BatchGet failed: %v", err)
			}
			if len(emptyResults) != 0 {
				t.Errorf("BATCH GET (empty): expected 0 results, got %d", len(emptyResults))
			}
		})
	}
}

func TestBatchAggregate(t *testing.T) {
	for _, drv := range []struct {
		name   string
		driver orm1.Driver
	}{
		{"sqlite", sqliteDriver},
		{"postgres", postgresDriver},
	} {
		t.Run(drv.name, func(t *testing.T) {
			ctx := context.Background()

			// Create session factory and register all entities
			registry := orm1.NewRegistry()
			registry.Register(&Purchase{}, orm1.WithTable("purchase"))
			registry.Register(&PurchaseLineItem{}, orm1.WithTable("purchase_line_item"))
			registry.Register(&PurchaseBilling{}, orm1.WithTable("purchase_billing"))
			registry.Register(&PurchaseBillingAttachment{}, orm1.WithTable("purchase_billing_attachment"))
			registry.Register(&PurchaseBillingPayment{}, orm1.WithTable("purchase_billing_payment"))
			registry.Register(&PurchaseWithdrawal{}, orm1.WithTable("purchase_withdrawal"))
			registry.Register(&PurchaseWithdrawalAttachment{}, orm1.WithTable("purchase_withdrawal_attachment"))
			factory := orm1.NewSessionFactory(registry, drv.driver)

			session := factory.CreateSession()

			// BATCH INSERT - Create multiple purchases with children
			customer1 := "customer-001"
			customer2 := "customer-002"
			customer3 := "customer-003"
			product1 := "product-1"
			product2 := "product-2"
			createdAt := int64(1234567890)
			remark := "test remark"

			purchases := []*Purchase{
				{
					ID:         "purchase-batch-001",
					CustomerID: &customer1,
					Price:      100.00,
					LineItems: []*PurchaseLineItem{
						{
							ID:         "line-batch-001",
							PurchaseID: "purchase-batch-001",
							ItemIndex:  1,
							Product:    &product1,
							Quantity:   2,
						},
					},
					Billings: []*PurchaseBilling{
						{
							ID:            "billing-batch-001",
							PurchaseID:    "purchase-batch-001",
							PaymentMethod: "credit_card",
							Amount:        100.00,
							BillingTime:   1234567890,
							Attachments: []*PurchaseBillingAttachment{
								{
									ID:                "billing-att-batch-001",
									PurchaseBillingID: "billing-batch-001",
									MediaURI:          "http://example.com/receipt1.pdf",
								},
							},
							Payment: &PurchaseBillingPayment{
								PurchaseBillingID: "billing-batch-001",
								PaymentTime:       1234567900,
								Amount:            100.00,
							},
						},
					},
					Withdrawal: &PurchaseWithdrawal{
						ID:         "withdrawal-batch-001",
						PurchaseID: "purchase-batch-001",
						CreatedAt:  &createdAt,
						Remark:     &remark,
						Attachments: []*PurchaseWithdrawalAttachment{
							{
								ID:                   "withdrawal-att-batch-001",
								PurchaseWithdrawalID: "withdrawal-batch-001",
								MediaURI:             "http://example.com/withdrawal1.pdf",
							},
						},
					},
				},
				{
					ID:         "purchase-batch-002",
					CustomerID: &customer2,
					Price:      200.00,
					LineItems: []*PurchaseLineItem{
						{
							ID:         "line-batch-002",
							PurchaseID: "purchase-batch-002",
							ItemIndex:  1,
							Product:    &product2,
							Quantity:   3,
						},
						{
							ID:         "line-batch-003",
							PurchaseID: "purchase-batch-002",
							ItemIndex:  2,
							Product:    &product1,
							Quantity:   1,
						},
					},
					Billings: []*PurchaseBilling{
						{
							ID:            "billing-batch-002",
							PurchaseID:    "purchase-batch-002",
							PaymentMethod: "paypal",
							Amount:        200.00,
							BillingTime:   1234567891,
							Payment: &PurchaseBillingPayment{
								PurchaseBillingID: "billing-batch-002",
								PaymentTime:       1234567901,
								Amount:            200.00,
							},
						},
					},
				},
				{
					ID:         "purchase-batch-003",
					CustomerID: &customer3,
					Price:      150.00,
					LineItems: []*PurchaseLineItem{
						{
							ID:         "line-batch-004",
							PurchaseID: "purchase-batch-003",
							ItemIndex:  1,
							Product:    &product1,
							Quantity:   5,
						},
					},
				},
			}

			err := session.BatchSave(ctx, purchases[0], purchases[1], purchases[2])
			if err != nil {
				t.Fatalf("BATCH INSERT: BatchSave failed: %v", err)
			}

			// BATCH GET - Verify cascade loading and order
			purchaseIDs := []orm1.Key{
				orm1.NewKey("purchase-batch-001"),
				orm1.NewKey("purchase-batch-002"),
				orm1.NewKey("purchase-batch-003"),
			}

			var results []*Purchase
			err = session.BatchGet(ctx, &results, purchaseIDs)
			if err != nil {
				t.Fatalf("BATCH GET: BatchGet failed: %v", err)
			}

			if len(results) != 3 {
				t.Fatalf("BATCH GET: expected 3 results, got %d", len(results))
			}

			// Verify order preservation
			if results[0].ID != "purchase-batch-001" {
				t.Errorf("BATCH GET: expected results[0].ID purchase-batch-001, got %s", results[0].ID)
			}
			if results[1].ID != "purchase-batch-002" {
				t.Errorf("BATCH GET: expected results[1].ID purchase-batch-002, got %s", results[1].ID)
			}
			if results[2].ID != "purchase-batch-003" {
				t.Errorf("BATCH GET: expected results[2].ID purchase-batch-003, got %s", results[2].ID)
			}

			// Verify cascade loading for first purchase
			if len(results[0].LineItems) != 1 {
				t.Errorf("BATCH GET: expected 1 line item for purchase-batch-001, got %d", len(results[0].LineItems))
			}
			if len(results[0].Billings) != 1 {
				t.Errorf("BATCH GET: expected 1 billing for purchase-batch-001, got %d", len(results[0].Billings))
			}
			if results[0].Billings[0].Payment == nil {
				t.Error("BATCH GET: expected payment to be loaded for purchase-batch-001")
			}
			if len(results[0].Billings[0].Attachments) != 1 {
				t.Errorf("BATCH GET: expected 1 attachment for purchase-batch-001, got %d", len(results[0].Billings[0].Attachments))
			}
			if results[0].Withdrawal == nil {
				t.Error("BATCH GET: expected withdrawal to be loaded for purchase-batch-001")
			} else if len(results[0].Withdrawal.Attachments) != 1 {
				t.Errorf("BATCH GET: expected 1 withdrawal attachment for purchase-batch-001, got %d", len(results[0].Withdrawal.Attachments))
			}

			// Verify cascade loading for second purchase
			if len(results[1].LineItems) != 2 {
				t.Errorf("BATCH GET: expected 2 line items for purchase-batch-002, got %d", len(results[1].LineItems))
			}
			if results[1].Withdrawal != nil {
				t.Error("BATCH GET: expected no withdrawal for purchase-batch-002")
			}

			// Verify cascade loading for third purchase
			if len(results[2].LineItems) != 1 {
				t.Errorf("BATCH GET: expected 1 line item for purchase-batch-003, got %d", len(results[2].LineItems))
			}
			if len(results[2].Billings) != 0 {
				t.Errorf("BATCH GET: expected no billings for purchase-batch-003, got %d", len(results[2].Billings))
			}

			// BATCH UPDATE - Modify multiple purchases
			results[0].Price = 110.00
			results[0].LineItems[0].Quantity = 10

			results[1].Price = 220.00
			product3 := "product-3"
			results[1].LineItems = append(results[1].LineItems, &PurchaseLineItem{
				ID:         "line-batch-005",
				PurchaseID: "purchase-batch-002",
				ItemIndex:  3,
				Product:    &product3,
				Quantity:   2,
			})

			results[2].Price = 160.00
			results[2].Withdrawal = &PurchaseWithdrawal{
				ID:         "withdrawal-batch-003",
				PurchaseID: "purchase-batch-003",
				CreatedAt:  &createdAt,
				Remark:     &remark,
			}

			err = session.BatchSave(ctx, results[0], results[1], results[2])
			if err != nil {
				t.Fatalf("BATCH UPDATE: BatchSave failed: %v", err)
			}

			// BATCH GET (after update) - Verify all changes
			var updatedResults []*Purchase
			err = session.BatchGet(ctx, &updatedResults, purchaseIDs)
			if err != nil {
				t.Fatalf("BATCH GET (after update): BatchGet failed: %v", err)
			}

			if updatedResults[0].Price != 110.00 {
				t.Errorf("BATCH GET (after update): expected price 110.00, got %f", updatedResults[0].Price)
			}
			if updatedResults[0].LineItems[0].Quantity != 10 {
				t.Errorf("BATCH GET (after update): expected quantity 10, got %d", updatedResults[0].LineItems[0].Quantity)
			}

			if updatedResults[1].Price != 220.00 {
				t.Errorf("BATCH GET (after update): expected price 220.00, got %f", updatedResults[1].Price)
			}
			if len(updatedResults[1].LineItems) != 3 {
				t.Errorf("BATCH GET (after update): expected 3 line items, got %d", len(updatedResults[1].LineItems))
			}

			if updatedResults[2].Price != 160.00 {
				t.Errorf("BATCH GET (after update): expected price 160.00, got %f", updatedResults[2].Price)
			}
			if updatedResults[2].Withdrawal == nil {
				t.Error("BATCH GET (after update): expected withdrawal to be added")
			}

			// BATCH GET with reversed order - Verify order preservation
			reversedIDs := []orm1.Key{
				orm1.NewKey("purchase-batch-003"),
				orm1.NewKey("purchase-batch-001"),
				orm1.NewKey("purchase-batch-002"),
			}

			var reversedResults []*Purchase
			err = session.BatchGet(ctx, &reversedResults, reversedIDs)
			if err != nil {
				t.Fatalf("BATCH GET (reversed): BatchGet failed: %v", err)
			}

			if reversedResults[0].ID != "purchase-batch-003" {
				t.Errorf("BATCH GET (reversed): expected results[0].ID purchase-batch-003, got %s", reversedResults[0].ID)
			}
			if reversedResults[1].ID != "purchase-batch-001" {
				t.Errorf("BATCH GET (reversed): expected results[1].ID purchase-batch-001, got %s", reversedResults[1].ID)
			}
			if reversedResults[2].ID != "purchase-batch-002" {
				t.Errorf("BATCH GET (reversed): expected results[2].ID purchase-batch-002, got %s", reversedResults[2].ID)
			}

			// BATCH DELETE - Verify cascade delete
			err = session.BatchDelete(ctx, updatedResults[0], updatedResults[1], updatedResults[2])
			if err != nil {
				t.Fatalf("BATCH DELETE: BatchDelete failed: %v", err)
			}

			// BATCH GET (after delete) - Verify all deleted
			var deletedResults []*Purchase
			err = session.BatchGet(ctx, &deletedResults, purchaseIDs)
			if err != nil {
				t.Fatalf("BATCH GET (after delete): BatchGet failed: %v", err)
			}

			for i, result := range deletedResults {
				if result != nil {
					t.Errorf("BATCH GET (after delete): expected results[%d] to be nil", i)
				}
			}
		})
	}
}
