package orm1_test

import (
	"context"
	"testing"

	"github.com/hanpama/orm1"
	"github.com/hanpama/orm1/driver"
)

func TestPersistenceSimpleAuto(t *testing.T) {
	for _, drv := range []struct {
		name   string
		driver driver.Driver
	}{
		{"sqlite", sqliteDriver},
		{"postgres", postgresDriver},
	} {
		t.Run(drv.name, func(t *testing.T) {
			ctx := context.Background()

			// Create session factory and register entity
			registry := orm1.NewRegistry()
			registry.Register(&SimpleAuto{}, orm1.WithTable("simple_auto"))
			factory := orm1.NewSessionFactory(registry, drv.driver)

			session := factory.CreateSession()
			var entityID int64

			// INSERT
			entity := &SimpleAuto{
				Name:     "test",
				Nullable: strPtr("nullable"),
			}

			err := session.Save(ctx, entity)
			if err != nil {
				t.Fatalf("INSERT: Save failed: %v", err)
			}

			if entity.ID == 0 {
				t.Fatal("INSERT: expected ID to be set")
			}
			if entity.AutoGenerated != 42 {
				t.Errorf("INSERT: expected AutoGenerated to be 42, got %d", entity.AutoGenerated)
			}

			entityID = entity.ID
			originalID := entity.ID

			// UPDATE (same entity instance, without Get)
			entity.Name = "test_immediate_update"
			err = session.Save(ctx, entity)
			if err != nil {
				t.Fatalf("UPDATE (immediate): Save failed: %v", err)
			}

			// Verify ID didn't change (proves UPDATE was used, not INSERT)
			if entity.ID != originalID {
				t.Errorf("UPDATE (immediate): ID changed from %d to %d - INSERT was used instead of UPDATE", originalID, entity.ID)
			}

			// GET (after insert)
			var found *SimpleAuto
			err = session.Get(ctx, &found, orm1.NewKey(entityID))
			if err != nil {
				t.Fatalf("GET: Get failed: %v", err)
			}

			if found == nil {
				t.Fatal("GET: expected entity to be found")
			}
			if found.Name != "test_immediate_update" {
				t.Errorf("GET: expected name 'test_immediate_update', got %s", found.Name)
			}
			if found.Nullable == nil || *found.Nullable != "nullable" {
				t.Error("GET: expected nullable field to be 'nullable'")
			}
			if found.AutoGenerated != 42 {
				t.Errorf("GET: expected AutoGenerated to be 42, got %d", found.AutoGenerated)
			}

			// UPDATE
			found.Name = "test_updated"
			found.Nullable = strPtr("nullable_updated")

			err = session.Save(ctx, found)
			if err != nil {
				t.Fatalf("UPDATE: Save failed: %v", err)
			}

			// GET (after update)
			var updated *SimpleAuto
			err = session.Get(ctx, &updated, orm1.NewKey(entityID))
			if err != nil {
				t.Fatalf("GET (after update): Get failed: %v", err)
			}

			if updated == nil {
				t.Fatal("GET (after update): expected entity to be found")
			}
			if updated.Name != "test_updated" {
				t.Errorf("GET (after update): expected name 'test_updated', got %s", updated.Name)
			}
			if updated.Nullable == nil || *updated.Nullable != "nullable_updated" {
				t.Error("GET (after update): expected nullable to be 'nullable_updated'")
			}

			// DELETE
			err = session.Delete(ctx, updated)
			if err != nil {
				t.Fatalf("DELETE: Delete failed: %v", err)
			}

			// GET (after delete)
			var deleted *SimpleAuto
			err = session.Get(ctx, &deleted, orm1.NewKey(entityID))
			if err != nil {
				t.Fatalf("GET (after delete): Get failed: %v", err)
			}

			if deleted != nil {
				t.Error("GET (after delete): expected entity to be nil")
			}
		})
	}
}

func TestPersistenceSimpleUUID(t *testing.T) {
	for _, drv := range []struct {
		name   string
		driver driver.Driver
	}{
		{"sqlite", sqliteDriver},
		{"postgres", postgresDriver},
	} {
		t.Run(drv.name, func(t *testing.T) {
			ctx := context.Background()

			// Create session factory and register entity
			registry := orm1.NewRegistry()
			registry.Register(&SimpleUUID{}, orm1.WithTable("simple_uuid"))
			factory := orm1.NewSessionFactory(registry, drv.driver)

			session := factory.CreateSession()

			// INSERT
			entityID := "550e8400-e29b-41d4-a716-446655440000" // test UUID
			entity := &SimpleUUID{
				ID:       entityID,
				Name:     "test",
				Nullable: strPtr("nullable"),
			}

			err := session.Save(ctx, entity)
			if err != nil {
				t.Fatalf("INSERT: Save failed: %v", err)
			}

			if entity.AutoGenerated != 42 {
				t.Errorf("INSERT: expected AutoGenerated to be 42, got %d", entity.AutoGenerated)
			}

			// GET (after insert)
			var found *SimpleUUID
			err = session.Get(ctx, &found, orm1.NewKey(entityID))
			if err != nil {
				t.Fatalf("GET: Get failed: %v", err)
			}

			if found == nil {
				t.Fatal("GET: expected entity to be found")
			}
			if found.ID != entityID {
				t.Errorf("GET: expected ID %s, got %s", entityID, found.ID)
			}
			if found.Name != "test" {
				t.Errorf("GET: expected name 'test', got %s", found.Name)
			}
			if found.Nullable == nil || *found.Nullable != "nullable" {
				t.Error("GET: expected nullable field to be 'nullable'")
			}
			if found.AutoGenerated != 42 {
				t.Errorf("GET: expected AutoGenerated to be 42, got %d", found.AutoGenerated)
			}

			// UPDATE
			found.Name = "test_updated"
			found.Nullable = strPtr("nullable_updated")

			err = session.Save(ctx, found)
			if err != nil {
				t.Fatalf("UPDATE: Save failed: %v", err)
			}

			// GET (after update)
			var updated *SimpleUUID
			err = session.Get(ctx, &updated, orm1.NewKey(entityID))
			if err != nil {
				t.Fatalf("GET (after update): Get failed: %v", err)
			}

			if updated == nil {
				t.Fatal("GET (after update): expected entity to be found")
			}
			if updated.Name != "test_updated" {
				t.Errorf("GET (after update): expected name 'test_updated', got %s", updated.Name)
			}
			if updated.Nullable == nil || *updated.Nullable != "nullable_updated" {
				t.Error("GET (after update): expected nullable to be 'nullable_updated'")
			}

			// DELETE
			err = session.Delete(ctx, updated)
			if err != nil {
				t.Fatalf("DELETE: Delete failed: %v", err)
			}

			// GET (after delete)
			var deleted *SimpleUUID
			err = session.Get(ctx, &deleted, orm1.NewKey(entityID))
			if err != nil {
				t.Fatalf("GET (after delete): Get failed: %v", err)
			}

			if deleted != nil {
				t.Error("GET (after delete): expected entity to be nil")
			}
		})
	}
}

func TestPersistenceComposite(t *testing.T) {
	for _, drv := range []struct {
		name   string
		driver driver.Driver
	}{
		{"sqlite", sqliteDriver},
		{"postgres", postgresDriver},
	} {
		t.Run(drv.name, func(t *testing.T) {
			ctx := context.Background()

			// Create session factory and register entity
			registry := orm1.NewRegistry()
			registry.Register(&Composite{},
				orm1.WithTable("composite"))
			factory := orm1.NewSessionFactory(registry, drv.driver)

			session := factory.CreateSession()

			// INSERT
			key1, key2 := 100, 200
			entity := &Composite{
				Key1:     key1,
				Key2:     key2,
				Name:     "test",
				Nullable: strPtr("nullable"),
			}

			err := session.Save(ctx, entity)
			if err != nil {
				t.Fatalf("INSERT: Save failed: %v", err)
			}

			if entity.AutoGenerated != 42 {
				t.Errorf("INSERT: expected AutoGenerated to be 42, got %d", entity.AutoGenerated)
			}

			// GET (after insert)
			var found *Composite
			err = session.Get(ctx, &found, orm1.NewKey(key1, key2))
			if err != nil {
				t.Fatalf("GET: Get failed: %v", err)
			}

			if found == nil {
				t.Fatal("GET: expected entity to be found")
			}
			if found.Key1 != key1 || found.Key2 != key2 {
				t.Errorf("GET: expected keys (%d,%d), got (%d,%d)", key1, key2, found.Key1, found.Key2)
			}
			if found.Name != "test" {
				t.Errorf("GET: expected name 'test', got %s", found.Name)
			}
			if found.Nullable == nil || *found.Nullable != "nullable" {
				t.Error("GET: expected nullable field to be 'nullable'")
			}
			if found.AutoGenerated != 42 {
				t.Errorf("GET: expected AutoGenerated to be 42, got %d", found.AutoGenerated)
			}

			// UPDATE
			found.Name = "test_updated"
			found.Nullable = strPtr("nullable_updated")

			err = session.Save(ctx, found)
			if err != nil {
				t.Fatalf("UPDATE: Save failed: %v", err)
			}

			// GET (after update)
			var updated *Composite
			err = session.Get(ctx, &updated, orm1.NewKey(key1, key2))
			if err != nil {
				t.Fatalf("GET (after update): Get failed: %v", err)
			}

			if updated == nil {
				t.Fatal("GET (after update): expected entity to be found")
			}
			if updated.Name != "test_updated" {
				t.Errorf("GET (after update): expected name 'test_updated', got %s", updated.Name)
			}
			if updated.Nullable == nil || *updated.Nullable != "nullable_updated" {
				t.Error("GET (after update): expected nullable to be 'nullable_updated'")
			}

			// DELETE
			err = session.Delete(ctx, updated)
			if err != nil {
				t.Fatalf("DELETE: Delete failed: %v", err)
			}

			// GET (after delete)
			var deleted *Composite
			err = session.Get(ctx, &deleted, orm1.NewKey(key1, key2))
			if err != nil {
				t.Fatalf("GET (after delete): Get failed: %v", err)
			}

			if deleted != nil {
				t.Error("GET (after delete): expected entity to be nil")
			}
		})
	}
}

func TestPersistenceSpecialQuote(t *testing.T) {
	for _, drv := range []struct {
		name   string
		driver driver.Driver
	}{
		{"sqlite", sqliteDriver},
		{"postgres", postgresDriver},
	} {
		t.Run(drv.name, func(t *testing.T) {
			ctx := context.Background()

			// Create session factory and register entity
			registry := orm1.NewRegistry()
			registry.Register(&SpecialQuote{},
				orm1.WithTable("special\"quote"))
			factory := orm1.NewSessionFactory(registry, drv.driver)

			session := factory.CreateSession()

			// INSERT
			entityID := "test-id-001"
			entity := &SpecialQuote{
				ID:         entityID,
				Name:       "test",
				FieldQuote: "quote_value",
				MixedCase:  "MixedCaseValue",
				Nullable:   strPtr("nullable"),
			}

			err := session.Save(ctx, entity)
			if err != nil {
				t.Fatalf("INSERT: Save failed: %v", err)
			}

			if entity.AutoGenerated != 42 {
				t.Errorf("INSERT: expected AutoGenerated to be 42, got %d", entity.AutoGenerated)
			}

			// GET (after insert)
			var found *SpecialQuote
			err = session.Get(ctx, &found, orm1.NewKey(entityID))
			if err != nil {
				t.Fatalf("GET: Get failed: %v", err)
			}

			if found == nil {
				t.Fatal("GET: expected entity to be found")
			}
			if found.ID != entityID {
				t.Errorf("GET: expected ID %s, got %s", entityID, found.ID)
			}
			if found.Name != "test" {
				t.Errorf("GET: expected name 'test', got %s", found.Name)
			}
			if found.FieldQuote != "quote_value" {
				t.Errorf("GET: expected FieldQuote 'quote_value', got %s", found.FieldQuote)
			}
			if found.MixedCase != "MixedCaseValue" {
				t.Errorf("GET: expected MixedCase 'MixedCaseValue', got %s", found.MixedCase)
			}
			if found.Nullable == nil || *found.Nullable != "nullable" {
				t.Error("GET: expected nullable field to be 'nullable'")
			}
			if found.AutoGenerated != 42 {
				t.Errorf("GET: expected AutoGenerated to be 42, got %d", found.AutoGenerated)
			}

			// UPDATE
			found.Name = "test_updated"
			found.FieldQuote = "quote_value_updated"
			found.MixedCase = "UpdatedMixedCase"
			found.Nullable = strPtr("nullable_updated")

			err = session.Save(ctx, found)
			if err != nil {
				t.Fatalf("UPDATE: Save failed: %v", err)
			}

			// GET (after update)
			var updated *SpecialQuote
			err = session.Get(ctx, &updated, orm1.NewKey(entityID))
			if err != nil {
				t.Fatalf("GET (after update): Get failed: %v", err)
			}

			if updated == nil {
				t.Fatal("GET (after update): expected entity to be found")
			}
			if updated.Name != "test_updated" {
				t.Errorf("GET (after update): expected name 'test_updated', got %s", updated.Name)
			}
			if updated.FieldQuote != "quote_value_updated" {
				t.Errorf("GET (after update): expected FieldQuote 'quote_value_updated', got %s", updated.FieldQuote)
			}
			if updated.MixedCase != "UpdatedMixedCase" {
				t.Errorf("GET (after update): expected MixedCase 'UpdatedMixedCase', got %s", updated.MixedCase)
			}
			if updated.Nullable == nil || *updated.Nullable != "nullable_updated" {
				t.Error("GET (after update): expected nullable to be 'nullable_updated'")
			}

			// DELETE
			err = session.Delete(ctx, updated)
			if err != nil {
				t.Fatalf("DELETE: Delete failed: %v", err)
			}

			// GET (after delete)
			var deleted *SpecialQuote
			err = session.Get(ctx, &deleted, orm1.NewKey(entityID))
			if err != nil {
				t.Fatalf("GET (after delete): Get failed: %v", err)
			}

			if deleted != nil {
				t.Error("GET (after delete): expected entity to be nil")
			}
		})
	}
}

func TestPersistenceAggregate(t *testing.T) {
	for _, drv := range []struct {
		name   string
		driver driver.Driver
	}{
		{"sqlite", sqliteDriver},
		{"postgres", postgresDriver},
	} {
		t.Run(drv.name, func(t *testing.T) {
			ctx := context.Background()

			// Create session factory and register all entities
			registry := orm1.NewRegistry()
			registry.Register(&Purchase{}, orm1.WithTable("purchase"))
			registry.Register(&PurchaseLineItem{}, orm1.WithTable("purchase_line_item"))
			registry.Register(&PurchaseBilling{}, orm1.WithTable("purchase_billing"))
			registry.Register(&PurchaseBillingAttachment{}, orm1.WithTable("purchase_billing_attachment"))
			registry.Register(&PurchaseBillingPayment{}, orm1.WithTable("purchase_billing_payment"))
			registry.Register(&PurchaseWithdrawal{}, orm1.WithTable("purchase_withdrawal"))
			registry.Register(&PurchaseWithdrawalAttachment{}, orm1.WithTable("purchase_withdrawal_attachment"))
			factory := orm1.NewSessionFactory(registry, drv.driver)

			session := factory.CreateSession()

			// INSERT - Create purchase with all children
			purchaseID := "purchase-001"
			customerID := "customer-001"
			product1 := "product-1"
			product2 := "product-2"
			createdAt := int64(1234567890)
			remark := "initial remark"

			purchase := &Purchase{
				ID:         purchaseID,
				CustomerID: &customerID,
				Price:      100.50,
				LineItems: []*PurchaseLineItem{
					{
						ID:         "line-001",
						PurchaseID: purchaseID,
						ItemIndex:  1,
						Product:    &product1,
						Quantity:   2,
					},
					{
						ID:         "line-002",
						PurchaseID: purchaseID,
						ItemIndex:  2,
						Product:    &product2,
						Quantity:   3,
					},
				},
				Billings: []*PurchaseBilling{
					{
						ID:            "billing-001",
						PurchaseID:    purchaseID,
						PaymentMethod: "credit_card",
						Amount:        100.50,
						BillingTime:   1234567890,
						Attachments: []*PurchaseBillingAttachment{
							{
								ID:                "billing-att-001",
								PurchaseBillingID: "billing-001",
								MediaURI:          "http://example.com/receipt1.pdf",
							},
						},
						Payment: &PurchaseBillingPayment{
							PurchaseBillingID: "billing-001",
							PaymentTime:       1234567900,
							Amount:            100.50,
						},
					},
				},
				Withdrawal: &PurchaseWithdrawal{
					ID:         "withdrawal-001",
					PurchaseID: purchaseID,
					CreatedAt:  &createdAt,
					Remark:     &remark,
					Attachments: []*PurchaseWithdrawalAttachment{
						{
							ID:                   "withdrawal-att-001",
							PurchaseWithdrawalID: "withdrawal-001",
							MediaURI:             "http://example.com/withdrawal1.pdf",
						},
					},
				},
			}

			err := session.Save(ctx, purchase)
			if err != nil {
				t.Fatalf("INSERT: Save failed: %v", err)
			}

			// GET - Verify cascade loading
			var found *Purchase
			err = session.Get(ctx, &found, orm1.NewKey(purchaseID))
			if err != nil {
				t.Fatalf("GET: Get failed: %v", err)
			}

			if found == nil {
				t.Fatal("GET: expected purchase to be found")
			}
			if found.Price != 100.50 {
				t.Errorf("GET: expected price 100.50, got %f", found.Price)
			}

			// Verify LineItems
			if len(found.LineItems) != 2 {
				t.Fatalf("GET: expected 2 line items, got %d", len(found.LineItems))
			}
			if found.LineItems[0].Quantity != 2 || found.LineItems[1].Quantity != 3 {
				t.Error("GET: line items quantities mismatch")
			}

			// Verify Billings with nested children
			if len(found.Billings) != 1 {
				t.Fatalf("GET: expected 1 billing, got %d", len(found.Billings))
			}
			if len(found.Billings[0].Attachments) != 1 {
				t.Errorf("GET: expected 1 billing attachment, got %d", len(found.Billings[0].Attachments))
			}
			if found.Billings[0].Payment == nil {
				t.Error("GET: expected billing payment to be loaded")
			} else if found.Billings[0].Payment.Amount != 100.50 {
				t.Errorf("GET: expected payment amount 100.50, got %f", found.Billings[0].Payment.Amount)
			}

			// Verify Withdrawal with attachments
			if found.Withdrawal == nil {
				t.Fatal("GET: expected withdrawal to be loaded")
			}
			if len(found.Withdrawal.Attachments) != 1 {
				t.Errorf("GET: expected 1 withdrawal attachment, got %d", len(found.Withdrawal.Attachments))
			}

			// UPDATE - Complex scenario
			// 1. Modify existing line item
			found.LineItems[0].Quantity = 5

			// 2. Add new line item
			product3 := "product-3"
			found.LineItems = append(found.LineItems, &PurchaseLineItem{
				ID:         "line-003",
				PurchaseID: purchaseID,
				ItemIndex:  3,
				Product:    &product3,
				Quantity:   1,
			})

			// 3. Delete one line item (remove line-002)
			found.LineItems = []*PurchaseLineItem{found.LineItems[0], found.LineItems[2]}

			// 4. Add new billing with attachments and payment
			found.Billings = append(found.Billings, &PurchaseBilling{
				ID:            "billing-002",
				PurchaseID:    purchaseID,
				PaymentMethod: "paypal",
				Amount:        50.25,
				BillingTime:   1234567950,
				Attachments: []*PurchaseBillingAttachment{
					{
						ID:                "billing-att-002",
						PurchaseBillingID: "billing-002",
						MediaURI:          "http://example.com/receipt2.pdf",
					},
					{
						ID:                "billing-att-003",
						PurchaseBillingID: "billing-002",
						MediaURI:          "http://example.com/receipt3.pdf",
					},
				},
				Payment: &PurchaseBillingPayment{
					PurchaseBillingID: "billing-002",
					PaymentTime:       1234567960,
					Amount:            50.25,
				},
			})

			// 5. Modify existing billing payment
			found.Billings[0].Payment.Amount = 110.00

			// 6. Add attachment to withdrawal
			found.Withdrawal.Attachments = append(found.Withdrawal.Attachments, &PurchaseWithdrawalAttachment{
				ID:                   "withdrawal-att-002",
				PurchaseWithdrawalID: "withdrawal-001",
				MediaURI:             "http://example.com/withdrawal2.pdf",
			})

			// 7. Update withdrawal remark
			newRemark := "updated remark"
			found.Withdrawal.Remark = &newRemark

			err = session.Save(ctx, found)
			if err != nil {
				t.Fatalf("UPDATE: Save failed: %v", err)
			}

			// GET (after update) - Verify all changes
			var updated *Purchase
			err = session.Get(ctx, &updated, orm1.NewKey(purchaseID))
			if err != nil {
				t.Fatalf("GET (after update): Get failed: %v", err)
			}

			// Verify LineItems changes
			if len(updated.LineItems) != 2 {
				t.Errorf("GET (after update): expected 2 line items, got %d", len(updated.LineItems))
			}
			// Find line-001 and verify quantity change
			var line001Found bool
			for _, item := range updated.LineItems {
				if item.ID == "line-001" {
					line001Found = true
					if item.Quantity != 5 {
						t.Errorf("GET (after update): expected line-001 quantity 5, got %d", item.Quantity)
					}
				}
				if item.ID == "line-002" {
					t.Error("GET (after update): line-002 should have been deleted")
				}
				if item.ID == "line-003" && item.Quantity != 1 {
					t.Errorf("GET (after update): expected line-003 quantity 1, got %d", item.Quantity)
				}
			}
			if !line001Found {
				t.Error("GET (after update): line-001 not found")
			}

			// Verify Billings changes
			if len(updated.Billings) != 2 {
				t.Errorf("GET (after update): expected 2 billings, got %d", len(updated.Billings))
			}
			for _, billing := range updated.Billings {
				if billing.ID == "billing-001" {
					if billing.Payment == nil || billing.Payment.Amount != 110.00 {
						t.Error("GET (after update): billing-001 payment amount should be 110.00")
					}
				}
				if billing.ID == "billing-002" {
					if len(billing.Attachments) != 2 {
						t.Errorf("GET (after update): expected 2 attachments for billing-002, got %d", len(billing.Attachments))
					}
					if billing.Payment == nil || billing.Payment.Amount != 50.25 {
						t.Error("GET (after update): billing-002 payment amount should be 50.25")
					}
				}
			}

			// Verify Withdrawal changes
			if len(updated.Withdrawal.Attachments) != 2 {
				t.Errorf("GET (after update): expected 2 withdrawal attachments, got %d", len(updated.Withdrawal.Attachments))
			}
			if updated.Withdrawal.Remark == nil || *updated.Withdrawal.Remark != "updated remark" {
				t.Error("GET (after update): withdrawal remark should be 'updated remark'")
			}

			// DELETE - Remove entire purchase (cascade delete)
			err = session.Delete(ctx, updated)
			if err != nil {
				t.Fatalf("DELETE: Delete failed: %v", err)
			}

			// GET (after delete) - Verify deletion
			var deleted *Purchase
			err = session.Get(ctx, &deleted, orm1.NewKey(purchaseID))
			if err != nil {
				t.Fatalf("GET (after delete): Get failed: %v", err)
			}

			if deleted != nil {
				t.Error("GET (after delete): expected purchase to be nil")
			}
		})
	}
}
