package orm1_test

// SimpleAuto - auto serial PK with all field attributes
type SimpleAuto struct {
	ID            int64 `orm1:"auto"`
	Name          string
	SkipInsert    string `orm1:"skip_insert"`
	SkipUpdate    string `orm1:"skip_update"`
	AutoGenerated int64  `orm1:"auto"`
	Nullable      *string
}

// SimpleUUID - user-assigned UUID PK with all field attributes
type SimpleUUID struct {
	ID            string // UUID
	Name          string
	SkipInsert    string `orm1:"skip_insert"`
	SkipUpdate    string `orm1:"skip_update"`
	AutoGenerated int64  `orm1:"auto"`
	Nullable      *string
}

// Composite - composite PK with all field attributes
type Composite struct {
	Key1          int
	Key2          int
	Name          string
	SkipInsert    string `orm1:"skip_insert"`
	SkipUpdate    string `orm1:"skip_update"`
	AutoGenerated int64  `orm1:"auto"`
	Nullable      *string
}

// SpecialQuote - natural key with special characters in table/column names
type SpecialQuote struct {
	ID            string // natural key
	Name          string
	FieldQuote    string  `orm1:"column:field\"quote"` // column name with "
	MixedCase     string  `orm1:"column:MixedCase"`    // column name with mixed case
	SkipInsert    string  `orm1:"skip_insert"`
	SkipUpdate    string  `orm1:"skip_update"`
	AutoGenerated int64   `orm1:"auto"`
	Nullable      *string
}

// Purchase - aggregate root with 3-level nested children
type Purchase struct {
	ID         string // natural key
	CustomerID *string
	Price      float64
	LineItems  []*PurchaseLineItem
	Billings   []*PurchaseBilling
	Withdrawal *PurchaseWithdrawal
}

type PurchaseLineItem struct {
	ID         string
	PurchaseID string `orm1:"parental"`
	ItemIndex  int64
	Product    *string
	Quantity   int64
}

type PurchaseBilling struct {
	ID            string
	PurchaseID    string `orm1:"parental"`
	PaymentMethod string
	Amount        float64
	BillingTime   int64
	Attachments   []*PurchaseBillingAttachment
	Payment       *PurchaseBillingPayment
}

type PurchaseBillingAttachment struct {
	ID                string
	PurchaseBillingID string `orm1:"parental"`
	MediaURI          string
}

type PurchaseBillingPayment struct {
	PurchaseBillingID string `orm1:"primary,parental"`
	PaymentTime       int64
	Amount            float64
}

type PurchaseWithdrawal struct {
	ID          string
	PurchaseID  string `orm1:"parental"`
	CreatedAt   *int64
	Remark      *string
	Attachments []*PurchaseWithdrawalAttachment
}

type PurchaseWithdrawalAttachment struct {
	ID                   string
	PurchaseWithdrawalID string `orm1:"parental"`
	MediaURI             string
}

// Pagination test entities
type BlogPost struct {
	ID          int64
	Title       string
	Rating      *int
	PublishedAt *int64
}

type BlogPostComposite struct {
	Key1        int64
	Key2        int64
	Title       string
	Rating      *int
	PublishedAt *int64
}

type BlogPostAggregate struct {
	ID          int64
	Title       string
	Rating      *int
	PublishedAt *int64
}

type BlogPostCommentAggregate struct {
	ID        int64
	PostID    int64
	Content   string
	CreatedAt *int64
}
