name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: docker:27.3.1-cli
    steps:
    - run: docker-compose up -d postgres
    - run: docker-compose run test
